In [16]:
import pandas as pd

data = {
    "Name": ["Danial", "Dias", "Olzhas", "Madina", "Nursultan"],
    "Age": [19, 21, 22, 20, 23],
    "Score": [85, 78, 92, 88, 75]
}

In [17]:
df.head(3)

      Name  Age  Score
0  Aruzhan   19     85
1     Dias   21     78
2    Aibek   22     92

In [18]:
df.describe()

             Age      Score
count   5.000000   5.000000
mean   21.000000  83.600000
std     1.581139   7.021396
min    19.000000  75.000000
25%    20.000000  78.000000
50%    21.000000  85.000000
75%    22.000000  88.000000
max    23.000000  92.000000

In [19]:
average_score = df["Score"].mean()
print("Average score:", average_score)

Average score: 83.6

In [20]:
df[df["Age"] > 20]

        Name  Age  Score
1       Dias   21     78
2      Aibek   22     92
4  Nursultan   23     75

In [23]:
df[df["Score"] > 80]

      Name  Age  Score
0  Aruzhan   19     85
2    Aibek   22     92
3   Madina   20     88